project:
  type: website
  output-dir: docs
  
website:
  title: "Daniel Amare"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
     
    tools:
      - icon: twitter
        href: https://twitter.com/
    background: warning
    foreground: danger
    search: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Daniel Amare"
    background: light

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    page-layout: full
    toc: true

editor: visual

